### ISSUE TITLE
Gearman getting started example is incorrect

### ISSUE THREAD

**Issue by tree28** [gearman/gearman.github.io#24]
Hello,

I submitted a post on another [forum](https://github.com/php/pecl-networking-gearman/issues/27) and was directed report the issue here.  The issue has to do with the getting started example from [here](https://gearman.org/getting-started/) (code shown below) because the "do" method is out of date.

`
$client= new GearmanClient();
$client->addServer();
print $client->do("reverse", "Hello World!");
`

**Comment by esabol** [comment]
A fix for this issue has been merged. @tree28 , please confirm and then close this issue if it looks OK to you. Thank you!
